import Head from "next/head";
import Image from "next/image";
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <>
        <div className={ styles.container }>
            <Head>
                <title>Recursos basicos do Next JS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/" />
            </Head>
        </div>
        <main className={ styles.main }>
            <h1>Teste</h1>
        </main>
        </>
    )
}